# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('begin_ap', models.CharField(choices=[('a', 'am'), ('p', 'pm')], default='a', max_length=1)),
                ('begin_hh', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='00', max_length=2)),
                ('begin_mi', models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default='00', max_length=2)),
                ('end_ap', models.CharField(choices=[('a', 'am'), ('p', 'pm')], default='a', max_length=1)),
                ('end_hh', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='00', max_length=2)),
                ('end_mi', models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default='00', max_length=2)),
                ('sel_attr', models.CharField(choices=[('%', 'All'), ('COOP', 'Coop'), ('CTL', 'Core Transfer Library'), ('CREX', 'Credit By Exam'), ('DPCR', 'Dept Credit'), ('DUAL', 'Dual Credit Transfer Work'), ('FTPV', 'Full-Time Privileges'), ('TC05', 'GTC-Humanistic-Artistic'), ('TC07', 'GTC-Information Literacy'), ('TC04', 'GTC-Quantitative Reasoning'), ('TC03', 'GTC-Science'), ('TC08', 'GTC-Science, Tech &amp; Society'), ('TC06', 'GTC-Social-Behavioral'), ('TC02', 'GTC-Speaking &amp; Listening'), ('TC01', 'GTC-Written Communication'), ('HONR', 'Honors'), ('IMPC', 'Impact Courses'), ('INTR', 'Internship'), ('LOWR', 'Lower Division'), ('MILT', 'Military'), ('PCOP', 'Parallel Coop'), ('PRCT', 'Practicum'), ('REMD', 'Remedial'), ('S01', 'S General Education'), ('S03', 'S Language &amp; Culture'), ('SL', 'Service Learning'), ('SGNL', 'Signal Courses'), ('STCH', 'Student Teaching'), ('TRIN', 'TransferIN'), ('UC06', 'UC-Behavior/Social Science'), ('UC05', 'UC-Humanities'), ('UC02', 'UC-Information Literacy'), ('UC03', 'UC-Oral Communications'), ('UC07', 'UC-Quantitative Reasoning'), ('UC04', 'UC-Science'), ('UC08', 'UC-Science, Tech &amp; Society'), ('UC01', 'UC-Written Communication'), ('UPPR', 'Upper Division'), ('VART', 'Variable Title')], default='%', max_length=50)),
                ('sel_camp', models.CharField(choices=[('%', 'All'), ('ICN', 'Indiana College Network'), ('TLF', 'Lafayette'), ('PWL', 'West Lafayette'), ('CEC', 'West Lafayette Continuing Ed')], default='%', max_length=50)),
                ('sel_day', multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednsay'), ('th', 'Thursday'), ('f', 'Friday')], max_length=10)),
                ('sel_insm', models.CharField(choices=[('%', 'All'), ('B/H', 'Hybrid'), ('DO', 'Online'), ('DPO', 'Primarily Online')], default='%', max_length=50)),
                ('sel_instr', models.CharField(default="['dummy', '%']", max_length=100, null=True)),
                ('sel_levl', models.CharField(default='%', max_length=50)),
                ('sel_ptrm', models.CharField(choices=[('%', 'All'), ('F8', 'First 8 Weeks'), ('1', 'Full Term'), ('LF', 'Lafayette'), ('S8', 'Second 8 Weeks')], default='%', max_length=50)),
                ('sel_schd', models.CharField(choices=[('%', 'All'), ('CLN', 'Clinic'), ('DIS', 'Distance Learning'), ('EX', 'Experiential'), ('IND', 'Individual Study'), ('LAB', 'Laboratory'), ('LBP', 'Laboratory Preparation'), ('LEC', 'Lecture'), ('PSO', 'Practice Study Observation'), ('PRS', 'Presentation'), ('REC', 'Recitation'), ('RES', 'Research'), ('SD', 'Studio')], default='%', max_length=50)),
                ('sel_sess', models.CharField(choices=[('%', 'All'), ('D', 'Day'), ('E', 'Evening'), ('I', 'Indiana College Network'), ('W', 'Weekend')], default='%', max_length=50)),
                ('sel_subj', models.CharField(max_length=50)),
                ('sel_title', models.CharField(blank=True, max_length=100)),
                ('sel_crse', models.CharField(max_length=10)),
                ('sel_from_cred', models.CharField(blank=True, max_length=2)),
                ('sel_to_cred', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
