# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('begin_ap', models.CharField(max_length=1)),
                ('begin_hh', models.CharField(max_length=2)),
                ('begin_mi', models.CharField(max_length=2)),
                ('end_ap', models.CharField(max_length=1)),
                ('end_hh', models.CharField(max_length=2)),
                ('end_mi', models.CharField(max_length=2)),
                ('sel_attr', models.CharField(max_length=50)),
                ('sel_camp', models.CharField(max_length=50)),
                ('sel_day', models.CharField(max_length=50)),
                ('sel_insm', models.CharField(max_length=50)),
                ('sel_instr', models.CharField(max_length=100)),
                ('sel_levl', models.CharField(max_length=50)),
                ('sel_ptrm', models.CharField(max_length=50)),
                ('sel_schd', models.CharField(max_length=50)),
                ('sel_sess', models.CharField(max_length=50)),
                ('sel_subj', models.CharField(max_length=50)),
                ('sel_title', models.CharField(max_length=100)),
                ('sel_crse', models.CharField(max_length=10)),
                ('sel_from_cred', models.CharField(max_length=2)),
                ('sel_to_cred', models.CharField(max_length=2)),
            ],
        ),
    ]
