# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sel_from_cred',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_to_cred',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
