# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0002_auto_20171129_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sel_instr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sel_levl',
        ),
    ]
