# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 20:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0003_auto_20171129_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sel_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednsay'), ('th', 'Thursday'), ('f', 'Friday')], default='%', max_length=10),
        ),
    ]
