# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0003_auto_20171128_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sel_attr',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_camp',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_day',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_insm',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_instr',
            field=models.CharField(default="['dummy', '%']", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_levl',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_ptrm',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_schd',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_sess',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_subj',
            field=models.CharField(default="['dummy', '%']", max_length=50, null=True),
        ),
    ]
