# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0004_auto_20171129_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sel_day',
        ),
    ]
