# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 20:51
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0007_auto_20171201_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sel_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednsay'), ('r', 'Thursday'), ('f', 'Friday'), ('s', 'Saturday'), ('u', 'Sunday')], default='%', max_length=13, verbose_name='Days'),
        ),
    ]
