# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0010_courses_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='User',
        ),
    ]
