# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0013_onesearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onesearch',
            old_name='email',
            new_name='emailAdd',
        ),
    ]
