# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0014_auto_20171205_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onesearch',
            name='emailAdd',
        ),
    ]
