# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0016_onesearch_subj'),
    ]

    operations = [
        migrations.AddField(
            model_name='onesearch',
            name='emailAdd',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
