# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_course', '0019_auto_20171208_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_hh',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='00', max_length=2, verbose_name='end hour'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='end_mi',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default='00', max_length=2, verbose_name='end minutes'),
        ),
    ]
